---
name: practical-07
break: true
indent: 4
---

src/main/java/practicalseven:
    MaxEfficiency.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 5
        MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment ">" --count 3
        MatchFileFragment --fragment ".getId()" --count 3
        MatchFileFragment --fragment ".getEfficiency()" --count 3
        MatchFileFragment --fragment "if" --count 3
        MatchFileFragment --fragment "else" --count 3
        
        
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle run -q --console plain run"
CountCommandOutput --command "gradle run -q --console plain run" --count 4